apiVersion: apps/v1
kind: Deployment
metadata:
  name: seal-miner-32g-calibnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seal-miner-32g-calibnet
  template:
    metadata:
      labels:
        app: seal-miner-32g-calibnet
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"miner-ipv4-ippool\"]"
    spec:
      nodeName: miner03
      containers:
      - name: seal-miner-32g-calibnet
        image: registry.cn-hangzhou.aliyuncs.com/ali_octopus/seal-miner:v0.7.19
        command: [ "sh", "-c", "start-miner.sh" ]
        volumeMounts:
        - name: daemon-config
          mountPath: /root/.lotus
          readOnly: true
        - name: miner-config
          mountPath: /root/.lotusminer
        - name: filecoin-parents
          mountPath: /var/tmp/filecoin-parents
        - name: filecoin-proof-parameters
          mountPath: /var/tmp/filecoin-proof-parameters
        - name: storage-store
          mountPath: /root/storage_store
        - name: sector-data
          mountPath: /root/sector-data
        - mountPath: /hugepages-1Gi
          name: hugepage-1gi
        resources:
          limits:
            hugepages-1Gi: 1784Gi
          requests:
            cpu: 8 
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OWNER_ADDRESS
          value: "t3s2366p74vwlo7vggvcy5jtwcvmemhtr655f7idkzro2r6bfhj5eiqaxhulu4l7bpbln5lshfmzdqrnyi5myq"
        - name: TASK_SET
          value: "taskset -c 1"
        - name: REDIS_OPTS
          value: "--redis-conn=192.168.203.3:6379,192.168.203.4:6379,192.168.203.5:6379 --redis-password=passwd123"
        - name: ABILITY_OPTS
          value: "--ability=PC1:27,PC2:2,C2:1"
        - name: RUST_BACKTRACE
          value: "full"
        - name: RUST_LOG
          value: "debug"
        - name: FIL_PROOFS_USE_MULTICORE_SDR
          value: "1"
        - name: FIL_PROOFS_MAXIMIZE_CACHING
          value: "1"
        - name: FIL_PROOFS_MULTICORE_SDR_PRODUCERS
          value: "1"
        - name: FIL_PROOFS_USE_GPU_COLUMN_BUILDER
          value: "1"
        - name: FIL_PROOFS_USE_GPU_TREE_BUILDER
          value: "1"
        - name: FIL_PROOFS_SDR_PARENTS_CACHE_SIZE
          value: "1073741824"
        - name: CC_SECTOR_DATA_PATH
          value: "/root/sector-data"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: LOG_PATH
          value: /root/.lotusminer/logs
      volumes:
      - name: daemon-config
        glusterfs:
          endpoints: glusterfs-cluster
          path: /sealed/calibnet/daemon
          readOnly: true
      - name: miner-config
        hostPath:
          path: /scratch/calibnet/MINER_ID
      - name: filecoin-parents
        hostPath:
          path: /scratch/calibnet/32g_proof/filecoin-parents
      - name: filecoin-proof-parameters
        hostPath:
          path: /scratch/calibnet/32g_proof/filecoin-proof-parameters
      - name: sector-data
        hostPath:
         path: /scratch/calibnet/pieces
      - name: storage-store
        glusterfs:
          endpoints: glusterfs-cluster
          path: /sealed/calibnet/storage/MINER_ID
      - name: hugepage-1gi
        emptyDir:
          medium: HugePages-1Gi
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: seal-miner-32g-calibnet
spec:
  type: ClusterIP
  clusterIP: 10.96.0.130
  ports:
  - port: 2345 
    targetPort: 2345
    name: seal-miner-32g-calibnet
  selector:
    app: seal-miner-32g-calibnet