apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: window-post-miner-32g-calibnet
spec:
  selector:
    matchLabels:
      app: window-post-miner-32g-calibnet
  template:
    metadata:
      labels:
        app: window-post-miner-32g-calibnet
      annotations:
        "cni.projectcalico.org/ipv4pools": "[\"miner-ipv4-ippool\"]"
    spec:
      nodeName: miner01
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      tolerations:
      - operator: Exists
      containers:
      - name: window-post-miner-32g-calibnet
        image: registry.cn-hangzhou.aliyuncs.com/ali_octopus/window-post-miner:v0.7.3
        command: [ "sh", "-c", "start-miner.sh" ]
        volumeMounts:
        - name: daemon-config
          mountPath: /root/.lotus
          readOnly: true
        - name: miner-config
          mountPath: /root/.lotusminer
        - name: filecoin-parents
          mountPath: /var/tmp/filecoin-parents
        - name: filecoin-proof-parameters
          mountPath: /var/tmp/filecoin-proof-parameters
        - name: storage-store
          mountPath: /root/storage_store
        - name: miner-logs
          mountPath: /root/logs
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OWNER_ADDRESS
          value: "t3s2366p74vwlo7vggvcy5jtwcvmemhtr655f7idkzro2r6bfhj5eiqaxhulu4l7bpbln5lshfmzdqrnyi5myq"
        - name: REDIS_OPTS
          value: "--redis-conn=192.168.203.3:6379,192.168.203.4:6379,192.168.203.5:6379 --redis-password=passwd123"
        - name: POST_OPTS
          value: "--enable-window-post=true"
        - name: FIL_PROOFS_MULTICORE_SDR_PRODUCERS
          value: "1"
        - name: FIL_PROOFS_SDR_PARENTS_CACHE_SIZE
          value: "1073741824"
        - name: FIL_PROOFS_MAXIMIZE_CACHING
          value: "1"
        - name: FIL_PROOFS_USE_MULTICORE_SDR
          value: "1"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: LOG_PATH
          value: "/root/logs"
      volumes:
      - name: daemon-config
        glusterfs:
          endpoints: glusterfs-cluster
          path: /sealed/calibnet/daemon
          readOnly: true
      - name: miner-config
        hostPath:
          path: /scratch/calibnet/miner-window-post-32g
      - name: filecoin-parents
        hostPath:
          path: /scratch/calibnet/32g_proof/filecoin-parents
      - name: filecoin-proof-parameters
        hostPath:
          path: /scratch/calibnet/32g_proof/filecoin-proof-parameters
      - name: storage-store
        glusterfs:
          endpoints: glusterfs-cluster
          path: /sealed/calibnet/storage/miner1
      - name: miner-logs
        hostPath:
          path: /scratch/calibnet/miner1/logs
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: window-post-miner-32g-calibnet
spec:
  type: ClusterIP
  clusterIP: 10.96.0.110
  ports:
  - port: 2346
    targetPort: 2345
    name: window-post-miner
  selector:
    app: window-post-miner-32g-calibnet
